language: ruby
cache: bundler
sudo: false
env:
- GOOGLE_SERVICE_ACCOUNT_ID=492957944163-ukbkb7l0su4d7u5pr7sgb8n5psijncm8@developer.gserviceaccount.com
before_install:
- openssl aes-256-cbc -K $encrypted_2108e06e9b37_key -iv $encrypted_2108e06e9b37_iv
  -in skuld-456631a502d6.p12.enc -out skuld-456631a502d6.p12 -d
- export GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY="$(openssl pkcs12 -in skuld-456631a502d6.p12
  -nocerts -passin pass:notasecret -nodes 2>/dev/null | openssl rsa 2>/dev/null)"
