#!/bin/sh

usage=$(cat <<USAGE
You need to install rerun and foreman to use this.

  gem install rerun foreman\n
USAGE)

command -v rerun >/dev/null 2>&1 || { echo >&2 "$usage"; exit 1; }
command -v foreman >/dev/null 2>&1 || { echo >&2 "$usage"; exit 1; }

rerun --ignore "**/*.haml" \
    -- foreman start
